config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  resources :api_tokens, only: [:index, :create, :update]

  get 'pages/home'
  get 'pages/api', as: :api

  get 'old_plannings', to: 'plannings#old_plannings', as: :old_plannings

  resources :reservations, only: [:create, :destroy]
  resources :plannings, only: [:index, :show] do
    resources :shifts, only: [:show]
  end
  resources :users, only: [:new, :create, :show, :patch] do
    patch :toggle_subscription, on: :member
    patch :toggle_advices, on: :member
  end

  get 'forgot_password', to: 'passwords#forgot_password', as: :forgot_password
  post 'send_password_reset_instructions', to: 'passwords#send_password_reset_instructions', as: :send_password_reset_instructions
  get 'reset_password', to: 'passwords#reset_password', as: :reset_password
  patch 'update_password', to: 'passwords#update_password', as: :update_password

  get 'onboarding', to: 'onboarding#onboarding', as: :onboarding
  put 'onboard', to: 'onboarding#onboard', as: :onboard
  put 'unboard', to: 'onboarding#unboard', as: :unboard

  get 'videos' => 'videos#index', :as => :videos
  put '/videos/:id/seen', to: 'videos#seen', as: 'video_seen'
  put '/videos/:id/unseen', to: 'videos#unseen', as: 'video_unseen'
  put '/videos/:id/complete', to: 'videos#complete', as: 'video_complete'
  get 'ultimate_advice' => 'videos#ultimate_advice', :as => :ultimate_advice

  post '/reviews', to: 'reviews#create', as: 'create_review'

  get 'profil' => 'users#show', :as => :profil

  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'users/activate/:id', to: 'users#activate', as: :activate_user

  get 'check_publications', to: 'publications#check', as: :check_publications

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        post 'candidate', to: 'authenticated#user_candidate'
        resources :plannings, only: [:index] do
          resources :shifts, only: [:index] do
            resources :reservations, only: [:create, :destroy]
          end
          resources :reservations, only: [:index]
        end
        match '*path', to: 'authenticated#not_found_route', via: :all
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Hashid::Rails

  authenticates_with_sorcery! do |config|
    config.submodules = [:remember_me, :activation, :reset_password]
  end

  before_validation :downcase_email

  validates :first_name, presence: true, on: :create
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, on: :create

  validates :email, uniqueness: true, presence: true
  validate :email_format

  has_many :reservations, dependent: :destroy
  has_many :shifts, through: :reservations

  has_many :api_tokens, dependent: :destroy
  has_many :api_requests, dependent: :destroy
  has_many :user_achievements, dependent: :destroy
  has_many :achievements, through: :user_achievements
  has_many :user_videos, dependent: :destroy
  has_many :videos, through: :user_videos

  has_many :plannings, class_name: "Planning", dependent: :destroy

  has_many :reviews, dependent: :destroy

  after_create :create_permanent_planning
  after_create :create_daily_planning

  MAX_API_REQUESTS_PER_10_MINUTE = 500

  def api_requests_within_last_10_minutes
    api_requests.where("created_at > ?", 10.minutes.ago).count
  end

  def api_requests_within_last_10_seconds
    api_requests.where("created_at > ?", 10.seconds.ago).count
  end

  def api_limit_exceeded?
    api_requests_within_last_10_minutes >= MAX_API_REQUESTS_PER_10_MINUTE
  end

  def create_permanent_planning
    planning = Planning.create_planning("permanent", self)
    planning.publish
  end

  def create_daily_planning
    plannings.where(planning_type: "daily", state: "available").update_all(state: "closed")
    planning = Planning.create_planning("daily", self)
    planning.publish
  end

  def record_achievement(key)
    achievement = Achievement.find_by(key: key)  
    return if self.achievements.include?(achievement)

    if achievement
      user_achievements.create(achievement: achievement)
    end
  end

  def has_all_achievements_for(video)
    video.achievements_count == self.achievements.where(video_id: video.id).count
  end

  def complete_video(video)
    return false if !has_all_achievements_for(video)

    user_videos.find_by(video: video).update(is_complete: true)
    user_videos.find_or_create_by(video: video.next_video) 
    update_level
    track_action("Shift Heroes - Complete video", { video: video.title, level: current_level })
  end

  def update_level
    videos_completed_count = self.user_videos.where(is_complete: true).count
    self.update(current_level: videos_completed_count)
    not_left_behind
  end

  def available_plannings(type = nil)
    plannings = Planning.available.where("user_id = ? OR planning_type = ?", self.id, 'weekly')
    plannings = plannings.where(planning_type: type) if type.present?
    plannings = plannings.order(planning_type: :asc)
  end

  def has_review?
    reviews.exists?
  end

  def can_review?
    current_level >= 6 && !has_review?
  end

  def last_video_accessible
    user_videos.sort_by { |uv| Video::CUSTOM_IDS_IN_ORDER.index(uv.video.custom_id) }.last&.video || Video.find_by(custom_id: "environment_and_api")
  end

  def track_action(event, properties = {})
    properties.merge!({ email: self.email })
    MixpanelTrackUserJob.perform_later(event, properties)
  end

  def add_to_mailing_list
    AddUserToMailingListJob.perform_later(self)
  end

  def not_left_behind
    return if subscribed_to_advices == false
    delay = adjust_delay_for_work_hours(6.hour)
    SendAdvicesToUserJob.set(wait: delay).perform_later(self.id, current_level)
  end

  def launch_account
    record_achievement('account_activation')
    user_videos.find_or_create_by(video: Video.first)
    track_action("Shift Heroes - Account activated")
    add_to_mailing_list
    not_left_behind
  end

  private

  def downcase_email
    self.email = email.downcase if email.present?
  end

  def email_format
    unless email =~ URI::MailTo::EMAIL_REGEXP
      errors.add(:email, "n'est pas valide")
    end
  end

  def adjust_delay_for_work_hours(minimum_delay)
    supposed_time = Time.now + minimum_delay
    supposed_hour = supposed_time.hour

    if supposed_hour < 8
      adjustment = (8 - supposed_hour).hours
    elsif supposed_hour > 20
      adjustment = (32 - supposed_hour).hours
    else
      return minimum_delay
    end

    days = (minimum_delay / 1.day).floor
    adjusted_delay = (days.days + adjustment) + (minimum_delay % 1.day)

    adjusted_delay
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:index, :show]
  before_action :check_onboarding, only: [:show]

  def show
    @user = current_user
    @subscribed_to_advices = @user.subscribed_to_advices
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to(:root, notice: "Lien d'activation envoyé à cet email: #{@user.email}")
    else
      flash.now[:alert] = "L'utilisateur n'a pas pu être créé : #{@user.errors.full_messages.join(', ')}"
      render :new, status: :unprocessable_entity
    end
  end

  def toggle_advices
    current_user.update(subscribed_to_advices: !current_user.subscribed_to_advices)
    @subscribed_to_advices = current_user.subscribed_to_advices

    respond_to do |format|
      format.turbo_stream
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      auto_login(@user)
      @user.launch_account

      redirect_to(onboarding_path, :notice => 'Ton compte est activé.')
    else
      not_authenticated
    end
  end

  def toggle_subscription
    current_user.update(subscribed_to_daily_planning: !current_user.subscribed_to_daily_planning)
    @subscribed_to_daily_planning = current_user.subscribed_to_daily_planning

    respond_to do |format|
      format.turbo_stream
    end
  end  

  private
    def user_params
      params.require(:user).permit(:first_name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<%= render "shared/flash" %>

<div class="container-md" style="max-width: 1140px;">
    <div class="row justify-content-center mb-3 mt-5 py-5">
        <div class="col-sm-8 text-center">
            <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-2">Démarrage imminent !</h1>
            <div class="progress mt-4" role="progressbar" aria-label="Example 20px high" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 90%">
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2 class="h5 mb-3 fw-bold">Tu es à un clic de commencer Shift Heroes !</h2>
            <%= form_with(model: User.new, url: users_path, method: :post, html: {class: "needs-validation", novalidate: ""}) do |f| %>
                <% if params[:email] && params[:email].present? %>
                    <%= f.label :email, value: "Ton email :", class: "form-label fw-bold" %>
                    <p>
                        <%= params[:email] %>
                        <%= link_to "(modifier)", root_path, class: "link" %>
                    </p>
                    <%= f.hidden_field :email, value: params[:email] %>
                <% else %>
                    <div class="mb-3">
                        <%= f.label :email, value: "Ton email :", class: "form-label fw-bold" %>
                        <%= f.email_field :email, class: "form-control form-control", required: true, placeholder: "Ton email" %>
                        <div class="invalid-feedback">Veuillez fournir une adresse e-mail valide.</div>
                    </div>
                <% end %>
                <div class="mb-3">
                    <%= f.label :first_name, value: "Ton prénom :", class: "form-label fw-bold" %>
                    <%= f.text_field :first_name, class: "form-control form-control", required: true, placeholder: "Ton prénom" %>
                    <div class="invalid-feedback">Veuillez fournir un prénom.</div>
                </div>
                <div class="mb-3">
                    <%= f.label :password, value: "Un mot de passe pour ton compte :", class: "form-label fw-bold" %>
                    <%= f.password_field :password, class: "form-control form-control", required: true, placeholder: "Un mot de passe pour ton compte" , oninput: "password_confirmation.value = this.value" %>
                    <div class="invalid-feedback">Veuillez fournir un mot de passe.</div>
                    <%= f.hidden_field :password_confirmation, id: "password_confirmation" %>
                </div>
                <div class="actions">
                    <%= f.submit "Démarrer", class: "btn border btn-lg px-4 me-md-2 bg-rainbow ms-0", style: "color: #0c5175; " %>
                </div>
            <% end %>
            <div class="row justify-content-center my-5">
                <div class="col-auto text-center">
                    <%= link_to login_path, method: :get, class: "px-4 mt-3 d-block" do %>
                        J'ai déjà un compte
                    <% end %>
                    <%= link_to root_path, method: :get, class: "px-4 mt-3 d-block" do %>
                        Retour à l'accueil
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= render "shared/navbar" %>
<%= render "shared/flash" %>

<div class="container-md">
  <div class="row justify-content-center text-center mt-5 mb-3">
      <div class="col-lg-8">
          <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">Ton profil</h1>
      </div>
  </div>
</div>

<div class="container-md rounded bg-white p-3 border" style="max-width:800px">
  <h5 class="mt-4">Tes informations de base :</h5>
  <p>
    Prénom : <%= @user.first_name %><br>
    Email : <%= @user.email %>
  </p>

  <h5 class="mt-4">Ta photo de profil :</h5>
  <img src="https://seccdn.libravatar.org/avatar/<%= Digest::MD5.hexdigest(@user.email.downcase) %>?s=100" alt="Profile Picture">
  
  <p>
    <%= link_to "Clique ici pour modifier ta photo de profil", "https://libravatar.org/", target: "_blank", class: "link-secondary" %>
  </p>

  <h5 class="mt-4">Relances par mail :</h5>
  
  <%= link_to toggle_advices_user_path(current_user), data: { turbo_method: :patch }, remote: true, class: "form-check form-switch", id: "toggle_advices_switch" do %>
    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchAdvices" <%= current_user.subscribed_to_advices ? 'checked' : '' %>>
    <label class="form-check-label text-secondary" for="flexSwitchAdvices"><%= current_user.subscribed_to_advices ? "Harry vous pousse à avancer par mail !" : "Harry ne vous pousse pas à avancer" %></label>
  <% end %>


  <h5 class="mt-4">Onboarding :</h5>

  <p>
    <%= link_to onboarding_path, class: "link-secondary" do %>
      <i class="fa-solid fa-video"></i>
      Cliquer ici pour revoir la vidéo d'introduction
    <% end %>
  </p>

  <p class="text-center mt-5 text-muted">
    <i class="fa-solid fa-envelope"></i>
    Tu rencontres un bug ? Contacte-moi sur support@joincodingnow.com
  </p>
</div>

app/views/users/toggle_advices.turbo_stream.erb
<%= turbo_stream.replace :toggle_advices_switch do %>
    <%= link_to toggle_advices_user_path(current_user), data: { turbo_method: :patch }, remote: true, class: "form-check form-switch", id: "toggle_advices_switch" do %>
        <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchAdvices" <%= current_user.subscribed_to_advices ? 'checked' : '' %>>
        <label class="form-check-label text-secondary" for="flexSwitchAdvices"><%= current_user.subscribed_to_advices ? "Harry vous pousse à avancer par mail !" : "Harry ne vous pousse pas à avancer" %></label>
    <% end %>
<% end %>

app/views/users/toggle_subscription.turbo_stream.erb
<%= turbo_stream.replace :toggle_subscription_switch do %>
    <%= link_to toggle_subscription_user_path(current_user), data: { turbo_method: :patch }, remote: true, class: "form-check form-switch", id: "toggle_subscription_switch" do %>
        <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" <%= current_user.subscribed_to_daily_planning ? 'checked disabled' : '' %>>
        <label class="form-check-label text-secondary text-muted" for="flexSwitchCheckChecked"><%= current_user.subscribed_to_daily_planning ? "Inscrit pour le prochain" : "S'inscrire pour le prochain" %></label>
    <% end %>
<% end %>