config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  resources :api_tokens, only: [:index, :create, :update]

  get 'pages/home'
  get 'pages/api', as: :api

  get 'old_plannings', to: 'plannings#old_plannings', as: :old_plannings

  resources :reservations, only: [:create, :destroy]
  resources :plannings, only: [:index, :show] do
    resources :shifts, only: [:show]
  end
  resources :users, only: [:new, :create, :show, :patch] do
    patch :toggle_subscription, on: :member
    patch :toggle_advices, on: :member
  end

  get 'forgot_password', to: 'passwords#forgot_password', as: :forgot_password
  post 'send_password_reset_instructions', to: 'passwords#send_password_reset_instructions', as: :send_password_reset_instructions
  get 'reset_password', to: 'passwords#reset_password', as: :reset_password
  patch 'update_password', to: 'passwords#update_password', as: :update_password

  get 'onboarding', to: 'onboarding#onboarding', as: :onboarding
  put 'onboard', to: 'onboarding#onboard', as: :onboard
  put 'unboard', to: 'onboarding#unboard', as: :unboard

  get 'videos' => 'videos#index', :as => :videos
  put '/videos/:id/seen', to: 'videos#seen', as: 'video_seen'
  put '/videos/:id/unseen', to: 'videos#unseen', as: 'video_unseen'
  put '/videos/:id/complete', to: 'videos#complete', as: 'video_complete'
  get 'ultimate_advice' => 'videos#ultimate_advice', :as => :ultimate_advice

  post '/reviews', to: 'reviews#create', as: 'create_review'

  get 'profil' => 'users#show', :as => :profil

  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'users/activate/:id', to: 'users#activate', as: :activate_user

  get 'check_publications', to: 'publications#check', as: :check_publications

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        post 'candidate', to: 'authenticated#user_candidate'
        resources :plannings, only: [:index] do
          resources :shifts, only: [:index] do
            resources :reservations, only: [:create, :destroy]
          end
          resources :reservations, only: [:index]
        end
        match '*path', to: 'authenticated#not_found_route', via: :all
      end
    end
  end
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
    <div class="alert alert-<%= bootstrap_class_for(type) %> alert-dismissible fade show position-fixed start-50 translate-middle-x" role="alert" style="z-index: 1050; box-shadow: 0px 3px 6px rgba(0,0,0,0.16); top: 1em; padding: 1em 4em 1em 3em;">
        <%= message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container-md">
    <hr class="text-muted mt-5" style="max-width: 200px; margin: 0 auto;">
    <footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4">
        <p class="col-md-12 mb-0 text-muted text-center small">
            Shiftheroes.fr – Une bonne raison d'apprendre le code !
        </p>
        <p class="col-md-12 mb-0 text-muted text-center small">
            <i class="fa-solid fa-code"></i> Créé en 2023 par <a href="https://harryjmg.fr" class="text-decoration-none">Harry Jmg</a> de <%= link_to "Coding Accelerator", "https://joincodingnow.com", class: "text-decoration-none" %> pour toi.
        </p>
    </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="row align-items-center my-5">
    <div class="col justify-content-center position-relative row">
      <div class="col-md-2 col-sm-4 col-6 px-3 mb-3">
        <%= link_to root_path do %>
          <%= image_tag "shiftheroes.png", id: "logo-shiftheroes", class: "img-fluid", style: "opacity: 0.7; margin-top: 1em;" %>
        <% end %>
      </div>
      <div class="col-md-8 col-sm-12 d-flex md-0 justify-content-center">
        <div class="col-auto">
            <%= button_active_to_block videos_path, method: :get, class: "btn btn-outline-secondary btn-sm px-4", style: "position: relative" do %>
              Ma progression
              <% if @new_videos_count > 0 %>
                <span id="success_notifications_badge" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                  <%= @new_videos_count %>
                  <span class="visually-hidden">notifications</span>
                </span>
              <% end %>
            <% end %>
        </div>
        <div class="col-auto">
            <%= button_active_to "Nos Plannings", plannings_path, method: :get, class: "btn btn-outline-secondary btn-sm px-4 me-md-2" %>
        </div>
        <div class="col-auto">
            <%= button_active_to "Documentation API", api_path, method: :get, class: "btn btn-outline-secondary btn-sm px-4 me-md-2" %>
        </div>
      </div>
      <div class="col-2 justify-content-end px-3">
        <div class="dropdown" style="padding-top: 0.8em">
          <a href="#" class="d-flex align-items-center text-secondary text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag "https://seccdn.libravatar.org/avatar/#{Digest::MD5.hexdigest(current_user.email.downcase)}?s=32", class: "rounded-circle me-2" %>
            <strong><%= current_user.first_name %> (lv.<%= current_user.current_level %>)</strong>
          </a>
          <ul class="dropdown-menu dropdown-menu-light text-small shadow" style="">
            <li><%= link_to "Mon profil", profil_path, class: "dropdown-item" %></li>
            <li><%= link_to "Mes résultats", old_plannings_path, class: "dropdown-item" %></li>
            <li><%= link_to "Mes tokens API", api_tokens_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Se déconnecter", :logout, data: { turbo_method: :post }, class: "dropdown-item" %></li>
          </ul>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/shared/_review_modal.html.erb
<div data-controller="review-modal" class="modal fade" id="reviewModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="reviewModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body p-4">
        <div id="error_messages_container">
          <div id="error_messages"></div>
        </div>
        <%= form_with model: Review.new, url: create_review_path, local: false do |f| %>
          <div class="mb-4" style="height: 5em;">
            <div class="star-rating">
              <h5>À quel point as-tu aimé Shift Heroes ?</h5>
              
              <fieldset class="rating mt-2">
                  <%= f.radio_button :stars, 10, id: "star5" %><label class="full" for="star5" title="Parfait - 5 étoiles"></label>
                  <%= f.radio_button :stars, 9, id: "star4half" %><label class="half" for="star4half" title="Quasi parfait - 4,5 étoiles"></label>
                  <%= f.radio_button :stars, 8, id: "star4" %><label class="full" for="star4" title="Super - 4 étoiles"></label>
                  <%= f.radio_button :stars, 7, id: "star3half" %><label class="half" for="star3half" title="Pas mal - 3,5 étoiles"></label>
                  <%= f.radio_button :stars, 6, id: "star3" %><label class="full" for="star3" title="Ça passe - 3 étoiles"></label>
                  <%= f.radio_button :stars, 5, id: "star2half" %><label class="half" for="star2half" title="Moyen - 2,5 étoiles"></label>
                  <%= f.radio_button :stars, 4, id: "star2" %><label class="full" for="star2" title="Assez bof - 2 étoiles"></label>
                  <%= f.radio_button :stars, 3, id: "star1half" %><label class="half" for="star1half" title="Mauvais - 1,5 étoiles"></label>
                  <%= f.radio_button :stars, 2, id: "star1" %><label class="full" for="star1" title="Je reste poli - 1 étoile"></label>
                  <%= f.radio_button :stars, 1, id: "starhalf" %><label class="half" for="starhalf" title="Claqué au sol - 0,5 étoile"></label>
              </fieldset>

            </div>
          </div>
          <div class="mb-2">
            <h5>Dépose ton avis public ici</h5>
            <%= f.text_area :comment, class: 'form-control mt-3', rows: 3, placeholder: "Shift Heroes est entrain de changer ma vie, merci Harry ! (ou un truc du genre)" %>
          </div>
          <div class="modal-footer border-0">
            <button type="button" class="btn link-secondary" data-bs-dismiss="modal">Plus tard</button>
            <%= f.submit "Je donne mon avis", class: 'btn bg-rainbow' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/create_review.turbo_stream.erb
<% if @review.errors.any? %>
  <%= turbo_stream.append "error_messages_container" do %>
    <div id="error_messages">
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        Dis-moi ce que tu as pensé de Shift Heroes, ça me permet de comprendre comment mieux t'aider !
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
  <% end %>
<% end %>