config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  resources :api_tokens, only: [:index, :create, :update]

  get 'pages/home'
  get 'pages/api', as: :api

  get 'old_plannings', to: 'plannings#old_plannings', as: :old_plannings

  resources :reservations, only: [:create, :destroy]
  resources :plannings, only: [:index, :show] do
    resources :shifts, only: [:show]
  end
  resources :users, only: [:new, :create, :show, :patch] do
    patch :toggle_subscription, on: :member
    patch :toggle_advices, on: :member
  end

  get 'forgot_password', to: 'passwords#forgot_password', as: :forgot_password
  post 'send_password_reset_instructions', to: 'passwords#send_password_reset_instructions', as: :send_password_reset_instructions
  get 'reset_password', to: 'passwords#reset_password', as: :reset_password
  patch 'update_password', to: 'passwords#update_password', as: :update_password

  get 'onboarding', to: 'onboarding#onboarding', as: :onboarding
  put 'onboard', to: 'onboarding#onboard', as: :onboard
  put 'unboard', to: 'onboarding#unboard', as: :unboard

  get 'videos' => 'videos#index', :as => :videos
  put '/videos/:id/seen', to: 'videos#seen', as: 'video_seen'
  put '/videos/:id/unseen', to: 'videos#unseen', as: 'video_unseen'
  put '/videos/:id/complete', to: 'videos#complete', as: 'video_complete'
  get 'ultimate_advice' => 'videos#ultimate_advice', :as => :ultimate_advice

  post '/reviews', to: 'reviews#create', as: 'create_review'

  get 'profil' => 'users#show', :as => :profil

  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'users/activate/:id', to: 'users#activate', as: :activate_user

  get 'check_publications', to: 'publications#check', as: :check_publications

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        post 'candidate', to: 'authenticated#user_candidate'
        resources :plannings, only: [:index] do
          resources :shifts, only: [:index] do
            resources :reservations, only: [:create, :destroy]
          end
          resources :reservations, only: [:index]
        end
        match '*path', to: 'authenticated#not_found_route', via: :all
      end
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def create
    @user = login(params[:email]&.downcase, params[:password], params[:remember_me])

    if @user
      redirect_to(:plannings, notice: 'Connexion réussie')
    else
      flash.now[:alert] = 'Connexion échouée'
      render action: 'new', status: :unprocessable_entity
    end
  end

  def destroy
    current_user.forget_me!
    logout
    redirect_to(:root, notice: 'Déconnexion réussie')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_with url: login_path, method: :post, html: {class: "needs-validation", novalidate: ""} do |f| %>
  <div class="mb-3">
    <%= f.label :email, class: "form-label" %>
    <%= f.text_field :email, class: "form-control", required: true %>
    <div class="invalid-feedback">Please provide an email.</div>
  </div>
  <div class="mb-3"> 
    <%= f.label :password, class: "form-label" %>
    <%= f.password_field :password, class: "form-control", required: true %>
    <div class="invalid-feedback">Please provide a password.</div>
  </div>
  <div class="actions">
    <%= f.submit "Se connecter", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<%= render "shared/flash" %>

<div class="container-md" style="max-width: 1140px;">
    <div class="row justify-content-center mb-3 mt-5 py-5">
        <div class="col-sm-8 text-center">
            <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-2">Reprise de l'aventure !</h1>
            <div class="progress mt-4" role="progressbar" aria-label="Example 20px high" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 90%">
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2 class="h5 mb-3 fw-bold">Connecte-toi pour continuer ton aventure sur Shift Heroes.</h2>
            <%= form_with(url: login_path, method: :post, html: {class: "needs-validation", novalidate: ""}) do |f| %>
                <div class="mb-3">
                    <%= f.label :email, class: "form-label fw-bold" %>
                    <%= f.email_field :email, class: "form-control form-control", required: true, placeholder: "Ton email" %>
                    <div class="invalid-feedback">Veuillez fournir une adresse e-mail valide.</div>
                </div>
                <div class="mb-3">
                    <%= f.label :password, class: "form-label fw-bold" %>
                    <%= f.password_field :password, class: "form-control form-control", required: true, placeholder: "Ton mot de passe" %>
                    <div class="invalid-feedback">Veuillez fournir un mot de passe.</div>
                </div>
                <div class="mb-3">
                    <%= link_to "Mot de passe oublié ?", forgot_password_path, class: "link" %>
                </div>
                <div class="form-check mb-3">
                    <%= f.check_box :remember_me, class: "form-check-input" %>
                    <%= f.label :remember_me, class: "form-label" do %>
                        Se souvenir de moi
                    <% end %>
                </div>
                <div class="actions">
                    <%= f.submit "Se connecter", class: "btn border btn-lg px-4 me-md-2 bg-rainbow ms-0", style: "color: #0c5175; " %>
                </div>
            <% end %>
            <div class="row justify-content-center my-5">
                <div class="col-auto text-center">
                    <%= link_to new_user_path, method: :get, class: "px-4 mt-3 d-block" do %>
                        Je n'ai pas encore de compte
                    <% end %>
                    <%= link_to root_path, method: :get, class: "px-4 mt-3 d-block" do %>
                        Retour à l'accueil
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>