config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  resources :api_tokens, only: [:index, :create, :update]

  get 'pages/home'
  get 'pages/api', as: :api

  get 'old_plannings', to: 'plannings#old_plannings', as: :old_plannings

  resources :reservations, only: [:create, :destroy]
  resources :plannings, only: [:index, :show] do
    resources :shifts, only: [:show]
  end
  resources :users, only: [:new, :create, :show, :patch] do
    patch :toggle_subscription, on: :member
    patch :toggle_advices, on: :member
  end

  get 'forgot_password', to: 'passwords#forgot_password', as: :forgot_password
  post 'send_password_reset_instructions', to: 'passwords#send_password_reset_instructions', as: :send_password_reset_instructions
  get 'reset_password', to: 'passwords#reset_password', as: :reset_password
  patch 'update_password', to: 'passwords#update_password', as: :update_password

  get 'onboarding', to: 'onboarding#onboarding', as: :onboarding
  put 'onboard', to: 'onboarding#onboard', as: :onboard
  put 'unboard', to: 'onboarding#unboard', as: :unboard

  get 'videos' => 'videos#index', :as => :videos
  put '/videos/:id/seen', to: 'videos#seen', as: 'video_seen'
  put '/videos/:id/unseen', to: 'videos#unseen', as: 'video_unseen'
  put '/videos/:id/complete', to: 'videos#complete', as: 'video_complete'
  get 'ultimate_advice' => 'videos#ultimate_advice', :as => :ultimate_advice

  post '/reviews', to: 'reviews#create', as: 'create_review'

  get 'profil' => 'users#show', :as => :profil

  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'users/activate/:id', to: 'users#activate', as: :activate_user

  get 'check_publications', to: 'publications#check', as: :check_publications

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        post 'candidate', to: 'authenticated#user_candidate'
        resources :plannings, only: [:index] do
          resources :shifts, only: [:index] do
            resources :reservations, only: [:create, :destroy]
          end
          resources :reservations, only: [:index]
        end
        match '*path', to: 'authenticated#not_found_route', via: :all
      end
    end
  end
end

app/models/planning.rb
class Planning < ApplicationRecord
    include Hashid::Rails

    belongs_to :user, optional: true

    has_many :shifts, dependent: :destroy
    has_many :reservations, through: :shifts, dependent: :destroy
    has_many :users, through: :reservations

    validates :name, presence: true
    validates :planning_type, presence: true
    validates :state, presence: true

    before_save :set_publication_date, if: -> { state_changed? && state == 'available' }

    scope :weekly, -> { where(planning_type: 'weekly') }
    scope :available, -> { where(state: 'available') }

    # States : draft, ready, available, closed, archived

    DAYS = ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"]

    
    def self.available_plannings
        Planning.where(state: "available").order(created_at: :desc).group_by(&:planning_type).map { |k, v| v.first }
    end
    
    def self.closed_plannings
        Planning.where(state: "closed").order(created_at: :desc)
    end
    
    def state_in_french
        if state == "draft"
            "Brouillon"
        elsif state == "ready"
            "Prêt"
        elsif state == "available"
            "Ouvert"
        elsif state == "closed"
            "Fermé"
        elsif state == "archived"
            "Archivé"
        end
    end
    
    def filling_rate
        return 0 if shifts.count == 0
        (shifts.sum(:seats_taken) / shifts.sum(:seats).to_f * 100).round(2)
    end

    def seats_left
        shifts.sum(:seats) - shifts.sum(:seats_taken)
    end
    
    def theme_color
        name.include?("hebdomadaire") ? "warning" : "success"
    end
    
    def description
        if planning_type == "permanent"
            "Ouvert en permanence pour que tu puisses t'entraîner."
        elsif planning_type == "daily"
            "Un planning d'entraînement publié tous les jours à 18h."
        elsif planning_type == "weekly"
            "Tous les samedis à 10h, bonne chance pour récupérer les créneaux."
        end
    end
    
    def order_by_type
        case planning_type
        when "permanent"
            1
        when "daily"
            2
        when "weekly"
            3
        end
    end

    def self.create_planning(type, user=nil)
        name = "Planning #{type}"
        planning = Planning.create!(name: name, planning_type: type, state: "draft", user: user)
        Planning::DAYS.each do |day|
            Planning.last.shifts.create!(day: day, start_hour: "08:00", end_hour: "14:00", seats: rand(10..15))
            Planning.last.shifts.create!(day: day, start_hour: "14:00", end_hour: "21:00", seats: rand(3..8))
        end
        planning
    end

    def publish
        update(state: "available")
    end

    def hourly_rate
        return 9 if planning_type == "weekly"
        0
    end

    def earnings(user)
        hourly_rate * reservations.where(user_id: user.id).sum { |r| r.duration_in_hours }
    end

    def self.available_types
        ["permanent", "daily", "weekly"]
    end

    def is_recent
        published_at > 5.minutes.ago
    end

    private
    
    def set_publication_date
        self.published_at = Time.now
    end
    
end

app/controllers/api/v1/plannings_controller.rb
class Api::V1::PlanningsController < Api::V1::AuthenticatedController
  before_action :set_planning, only: [:show, :update, :destroy]

  def index
    available_types = Planning.available_types
    valid_params = %w[action controller type format]
  
    return unless check_unexpected_params(valid_params)
    return unless check_expected_param(:type, available_types)
  
    @plannings = current_user.available_plannings(params[:type])
    current_user.record_achievement('list_plannings_with_python') if python_used
  
    render json: @plannings.map { |planning| { id: planning.hashid, planning_type: planning.planning_type, state: planning.state, published_at: planning.published_at } }
  end

  private

  def check_expected_param(param_name, available_values)
    value = params[param_name]
    if value.present? && !available_values.include?(value)
      render json: { error: "Invalid #{param_name}. Available #{param_name}s are: #{available_values.join(', ')}" }, status: :unprocessable_entity
      return false
    end
    true
  end
  
  def check_unexpected_params(valid_params)
    unexpected_params = params.keys - valid_params
    if unexpected_params.any?
      render json: { error: "Unexpected parameters detected: #{unexpected_params.join(', ')}." }, status: :unprocessable_entity
      return false
    end
    true
  end

  def set_planning
    @planning = Planning.find(params[:id])
  end
end

app/controllers/plannings_controller.rb
class PlanningsController < ApplicationController
  before_action :require_login
  before_action :check_onboarding
  
  # GET /plannings or /plannings.json
  def index
    @permanent_planning = current_user.plannings.where(planning_type: 'permanent', state: 'available').first
    @daily_planning = current_user.plannings.where(state: 'available', planning_type: 'daily').order(published_at: :desc).first
    @weekly_planning = Planning.where(planning_type: 'weekly', state: 'available').order(published_at: :desc).first

    @available_plannings = [@permanent_planning, @daily_planning, @weekly_planning].compact
  end

  def old_plannings
    @plannings = current_user.plannings.where(planning_type: 'daily')
    @plannings += Planning.where(planning_type: 'weekly')
    @plannings = @plannings.sort_by(&:published_at).reverse
  end

  # GET /plannings/1 or /plannings/1.json
  def show
    @planning = Planning.find(params[:id])
    @user_shifts = current_user.shifts.where(planning_id: @planning.id)
  end
end

app/helpers/plannings_helper.rb
module PlanningsHelper
end

app/views/plannings/_planning.html.erb
<% if this_planning.planning_type == "weekly" %>
  <div class="col-lg-4 border rounded-4 me-4 mb-4 py-4 bg-rainbow">
    <div class="training_planning">
      <%= link_to planning_path(this_planning), style: "text-decoration:none" do %>
        <div class="icon my-5 text-center">
          <span class="text">n°<%= this_planning.published_at.strftime('%U') %></span>
        </div>
        <div class="details">
          <p class="text-muted text-center">
            <strong><%= this_planning.seats_left %>/14</strong> créneaux disponibles
          </p>
          <p class="text-muted text-center">
            Publié il y a <%= time_ago_in_words(this_planning.published_at) %><br>
            Prochain : <span id="weeklyCountdown" data-controller="countdown"></span>
          </p>
          <p class="text-muted text-center">
            <strong><%= user_slots = this_planning.reservations.where(user_id: current_user.id).count %></strong> créneaux obtenus <%= evaluate_performance(user_slots) %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
<% else %>

  <div class="col-lg-4 border rounded-4 me-4 mb-4 py-4">
    <div class="training_planning">
      <%= link_to planning_path(this_planning), style: "text-decoration:none" do %>
        <div class="icon my-5">
          <% if this_planning.planning_type == "permanent" %>
            <i class="fa-solid fa-infinity"></i>
          <% else %>
            <i class="fa-solid fa-calendar-day <%= "fa-beat" if this_planning.is_recent %>"></i>
          <% end %>
        </div>
      <% end %>
      <div class="details">
        <p class="text-muted text-center">
          <% if this_planning.planning_type == "daily" %>
            Planning journalier du <%= this_planning.published_at.strftime('%d/%m') %> à <%= (this_planning.published_at + 2.hours).strftime('%H:%M') %><br>
            Prochain dans : <span id="dailyCountdown" data-controller="countdown"></span>
          <% else %>
            Planning permanent<br>
            Toujours disponible
          <% end %>
        </p>
      </div>
      <% if this_planning.planning_type == "daily" %>
        <div class="d-flex justify-content-center">
          <%= link_to toggle_subscription_user_path(current_user), data: { turbo_method: :patch }, remote: true, class: "form-check form-switch", id: "toggle_subscription_switch" do %>
            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" <%= current_user.subscribed_to_daily_planning ? 'checked disabled' : '' %>>
            <label class="form-check-label text-secondary text-muted" for="flexSwitchCheckChecked"><%= current_user.subscribed_to_daily_planning ? "Inscrit pour le prochain" : "Cliquer pour le recevoir" %></label>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

<% end %>

app/views/plannings/_shift.html.erb
<td>
    <div class="d-grid gap-2">
        <%= button_tag "#{shift.start_hour}-#{shift.end_hour} (#{shift.seats_taken}/#{shift.seats})", type: "button", class: "btn btn-primary", data: { bs_toggle: "modal", bs_target: "#modal#{shift.id}" } %>
    </div>
</td>

<div class="modal fade" id="modal<%= shift.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <%= shift.day.capitalize %> - <%= shift.start_hour %> à <%= shift.end_hour %>
                <br>
                Places : <%= shift.seats_taken %> / <%= shift.seats %>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <%= turbo_frame_tag dom_id(shift) do %>
                    <% if @user_shifts.include?(shift) %>
                        <% reservation = current_user.reservations.find_by(shift_id: shift.id) %>
                        <%= button_to "Annuler la réservation", reservation, method: :delete, class: "btn btn-warning" %>
                    <% elsif shift.seats_taken < shift.seats %>
                        <%= button_to "Réserver", reservations_url, params: { reservation: { shift_id: shift.id, user_id: current_user.id } }, class: "btn btn-primary" %>
                    <% else %>
                        <%= button_to "Réserver", reservations_url, params: { reservation: { shift_id: shift.id, user_id: current_user.id } }, class: "btn btn-primary", disabled: true %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/plannings/index.html.erb
<%= render "shared/navbar" %>
<%= render "shared/flash" %>

<div class="container-md">
  <div class="row justify-content-center text-center mt-5 mb-3">
      <div class="col-lg-8">
          <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">Mode réel</h1>
          <p class="lead">Tous les utilisateurs sont en compétition. Que le plus rapide gagne.</p>
      </div>
  </div>
</div>

<% if @weekly_planning %>
  <div class="container row justify-content-center" id="real_plannings">
    <div class="col-10 row justify-content-center">
      <%= render "plannings/planning", this_planning: @weekly_planning %>
    </div>
  </div>
<% end %>

<div class="container-md">
  <div class="row justify-content-center text-center mt-5 mb-3">
    <div class="col-lg-8">
      <h2 class="display-6 fw-bold text-body-emphasis lh-1 mb-3">Mode entraînement</h2>
      <p class="lead">Ces deux plannings ne sont accessibles qu'à toi.</p>
    </div>
  </div>
</div>

<div class="container row justify-content-center" id="training_plannings">
  <div class="col-10 row justify-content-center">
    <%= render "plannings/planning", this_planning: @permanent_planning %>
    <%= render "plannings/planning", this_planning: @daily_planning %>
  </div>
</div>

app/views/plannings/old_plannings.html.erb
<%= render "shared/navbar" %>
<%= render "shared/flash" %>

<div class="container-md">
  <div class="row justify-content-center text-center mt-5 mb-3">
    <div class="col-lg-8">
      <h2 class="display-6 fw-bold text-body-emphasis lh-1 mb-3">Tes anciens résultats</h2>
      <p class="lead">Ces plannings hebdomadaires sont déjà passés, mais tu peux toujours voir tes résultats.</p>
    </div>
  </div>
</div>


<div class="container-sm mt-5" style="max-width:780px">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Heure</th>

        <th scope="col">Type</th>
        <th scope="col">Créneaux obtenus</th>
        <th scope="col">Revenus obtenus</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
        <% @plannings.each_with_index do |planning, index| %>
            <tr>
                    <td><%= planning.published_at.strftime("%d/%m/%Y") %> </td>
                    <td><%= planning.published_at.strftime("%H:%M") %></td>
                    <td><%= planning.planning_type %></td>
                    <td><%= planning.reservations.where(user_id: current_user.id).count %>/<%= planning.shifts.count %></td>
                    <td>
                        <%= planning.hourly_rate > 0 ? number_to_currency(planning.earnings(current_user), unit: "€") : "–" %>
                    </td>
                    <td>
                        <%= link_to "Ouvrir", planning_path(planning), class: "link-secondary" %>
                    </td>
            </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/plannings/show.html.erb
<%= render "shared/navbar" %>

<div class="container-md">
    <div class="row justify-content-center text-center mt-5 mb-3">
        <div class="col-lg-8">
            <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">Planning de semaine n°<%= @planning.published_at.strftime("%W") %></h1>
            <p class="lead">
              Publié il y a <%= distance_of_time_in_words(Time.now, @planning.published_at) %>
            </p>
        </div>
    </div>
</div>

<p style="color: green"><%= notice %></p>

<div class="container-md mb-5">
  <table class="table table-borderless shifts">
    <thead style="text-align: center; text-transform: capitalize;">
      <tr>
        <th scope="col"></th>
        <% "lundi mardi mercredi jeudi vendredi samedi dimanche".split(" ").each_with_index do |day_name, day| %>
          <th scope="col"><%= day_name %></th> <!-- Affiche le jour de la semaine -->
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% [8, 14].each do |hour| %>
        <tr>
          <td><%= '%02d:00' % hour %></td> <!-- Affiche l'heure -->
          <% "lundi mardi mercredi jeudi vendredi samedi dimanche".split(" ").each_with_index do |day_name, day| %>
            <td>
              <% @planning.shifts.where(day: day_name.downcase).each do |shift| %> <!-- Boucle à travers les shifts pour le jour actuel -->
                <% if shift.start_hour.hour == hour %>
                  <%= link_to planning_shift_path(@planning, shift) do %>
                    <div class="event rounded border <%= 'reserved bg-rainbow' if current_user.shifts.include?(shift) %> <%= 'full' if shift.seats_taken == shift.seats %>">
                      <%= shift.start_hour.strftime("%H:%M") %> - <%= shift.end_hour.strftime("%H:%M") %>
                      <div>
                        Places: <%= shift.seats_taken %> / <%= shift.seats %>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>


</div>

<div class="container-md text-center mt-4">
  <p>
    <%= link_to plannings_path, class: "link-secondary" do %>
      <i class="fa-solid fa-arrow-right-from-bracket"></i>
      Retour aux plannings
    <% end %>
  </p>
</div>